# Generated by Django 3.2 on 2021-05-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0002_alter_event_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='my-slug', max_length=250, unique_for_date='pub_date'),
            preserve_default=False,
        ),
    ]
