# Generated by Django 3.2 on 2021-05-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0005_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
