# Generated by Django 3.2 on 2021-05-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0008_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='pub_date'),
        ),
    ]
